In [1]:
import pandas as pd
import numpy as np

In [2]:
people = {
    'first':['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last':['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email':['corey@gmail.com', 'jane@gmail.com', 'john@gmail.com', None, np.nan, 'anonymous@gmail.com', 'NA'],
    'age':['33', '55', '63', '36', None, None, 'Missing']
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                email      age
0  Corey  Schafer      corey@gmail.com       33
1   Jane      Doe       jane@gmail.com       55
2   John      Doe       john@gmail.com       63
3  Chris  Schafer                 None       36
4    NaN      NaN                  NaN     None
5   None      NaN  anonymous@gmail.com     None
6     NA  Missing                   NA  Missing

## dropna()
Syntax:<br>
dropna()
<br>

Default parameters: <br>
dropna(axis = 'index', how = 'any')

'index' means look up by the rows<br>
'any' means, drop if even any of the columns in the row has missing value<br>
---> This means, drop any row that has any num of missing value, be it just 1 or many <br>

We could set this to:<br>
dropna(axis = 'index', how = 'all')<br>
---> This would drop only rows where all the values(columns) are missing<br>


We could set this to:<br>
dropna(axis = 'column',  how = 'any')<br>
---> This would drop the column where even a single value is missing<br>

We could set this to:<br>
dropna(axis = 'column', how = 'all')
---> This would drop the columns where all the values are missing<br>


<b>NOTE: </b><br>
The axis parameter takes two possible arguments:
index or columns

The how paramenter takes two possible arguments:

In [5]:
df.dropna()

   first     last            email      age
0  Corey  Schafer  corey@gmail.com       33
1   Jane      Doe   jane@gmail.com       55
2   John      Doe   john@gmail.com       63
6     NA  Missing               NA  Missing

In [7]:
#Alternative for above
#Same as above
df.dropna(axis = 'index', how = 'any')

   first     last            email      age
0  Corey  Schafer  corey@gmail.com       33
1   Jane      Doe   jane@gmail.com       55
2   John      Doe   john@gmail.com       63
6     NA  Missing               NA  Missing